from django.urls import path
from . import views

urlpatterns = [
    path('terrains/<int:pk>/',views.TerrainView.as_view()),
    path('terrains/<int:pk>/',views.TerrainViewRM.as_view()),
    path('terrains/<int:pk>/',views.TerrainViewUpdate.as_view()),
    path('terrains/search/',views.TerrainViewSearch.as_view()),
    path('terrains/search2/',views.TerrainViewSearchV2.as_view()),
    path('terrains/insert/',views.TerrainViewInsert.as_view()),
    path('terrains/delete/<int:pk>/',views.TerrainViewRM.as_view()),

    path('clubs/<int:pk>/',views.ClubView.as_view()),
    path('clubs/<int:pk>/',views.ClubViewRM.as_view()),
    path('clubs/<int:pk>/',views.ClubViewUpdate.as_view()),
    path('clubs/search/',views.ClubViewSearch.as_view()),
    path('clubs/search2/',views.ClubViewSearchV2.as_view()),
    path('clubs/insert/',views.ClubViewInsert.as_view()),
    path('clubs/searchEmail/',views.ClubViewSearchEmail.as_view()),
    path('clubs/delete/<int:pk>/',views.ClubViewRM.as_view()),

    path('admins/<int:pk>/',views.AdminView.as_view()),
    path('admins/<int:pk>/',views.AdminViewUpdate.as_view()),
    path('admins/searchEmail/',views.AdminViewSearch.as_view()),
    path('admins/insert/',views.AdminViewInsert.as_view()),

    path('postes/<int:pk>/',views.PosteView.as_view()),
    path('postes/<int:pk>/',views.PosteViewRM.as_view()),
    path('postes/<int:pk>/',views.PosteViewUpdate.as_view()),
    path('postes/search/',views.PosteViewSearch.as_view()),
    path('postes/search2/',views.PosteViewSearchV2.as_view()),
    path('postes/insert/',views.PosteViewInsert.as_view()),

    path('joueurs/<int:pk>/',views.JoueurView.as_view()),
    path('joueurs/<int:pk>/',views.JoueurViewRM.as_view()),
    path('joueurs/update/<int:pk>/',views.JoueurViewUpdate.as_view()),
    path('joueurs/search/',views.JoueurViewSearch.as_view()),
    path('joueurs/search2/',views.JoueurViewSearchV2.as_view()),
    path('joueurs/insert/',views.JoueurViewInsert.as_view()),
    path('joueurs/searchEmail/',views.JoueurViewSearchEmail.as_view()),
    path('joueurs/delete/<int:pk>/',views.JoueurViewRM.as_view()),

    path('entraineurs/<int:pk>/',views.EntraineurView.as_view()),
    path('entraineurs/<int:pk>/',views.EntraineurViewRM.as_view()),
    path('entraineurs/update/<int:pk>/',views.EntraineurViewUpdate.as_view()),
    path('entraineurs/search/',views.EntraineurViewSearch.as_view()),
    path('entraineurs/search2/',views.EntraineurViewSearchV2.as_view()),
    path('entraineurs/insert/',views.EntraineurViewInsert.as_view()),
    path('entraineurs/searchEmail/',views.EntraineurViewSearchEmail.as_view()),
    path('entraineurs/delete/<int:pk>/',views.EntraineurViewRM.as_view()),

    path('arbitres/<int:pk>/',views.ArbitreView.as_view()),
    path('arbitres/<int:pk>/',views.ArbitreViewRM.as_view()),
    path('arbitres/<int:pk>/',views.ArbitreViewUpdate.as_view()),
    path('arbitres/search/',views.ArbitreViewSearch.as_view()),
    path('arbitres/search2/',views.ArbitreViewSearchV2.as_view()),
    path('arbitres/insert/',views.ArbitreViewInsert.as_view()),
    path('arbitres/delete/<int:pk>/',views.ArbitreViewRM.as_view()),

    path('spectateurs/<int:pk>/',views.SpectateurView.as_view()),
    path('spectateurs/<int:pk>/',views.SpectateurViewRM.as_view()),
    path('spectateurs/<int:pk>/',views.SpectateurViewUpdate.as_view()),
    path('spectateurs/search/',views.SpectateurViewSearch.as_view()),
    path('spectateurs/search2/',views.SpectateurViewSearchV2.as_view()),
    path('spectateurs/insert/',views.SpectateurViewInsert.as_view()),
    path('spectateurs/searchEmail/',views.SpectateurViewSearchEmail.as_view()),
    path('spectateurs/delete/<int:pk>/',views.SpectateurViewRM.as_view()),

    path('equipes/<int:pk>/',views.EquipeView.as_view()),
    path('equipes/<int:pk>/',views.EquipeViewRM.as_view()),
    path('equipes/<int:pk>/',views.EquipeViewUpdate.as_view()),
    path('equipes/search/',views.EquipeViewSearch.as_view()),
    path('equipes/search2/',views.EquipeViewSearchV2.as_view()),
    path('equipes/insert/',views.EquipeViewInsert.as_view()),
    path('equipes/searchJoueur/',views.EquipeViewSearchJoueur.as_view()),
    path('equipes/delete/<int:pk>/',views.EquipeViewRM.as_view()),



    path('matchs/<int:pk>/',views.MatchView.as_view()),
    path('matchs/<int:pk>/',views.MatchViewRM.as_view()),
    path('matchs/<int:pk>/',views.MatchViewUpdate.as_view()),
    path('matchs/search/',views.MatchViewSearch.as_view()),
    path('matchs/search2/',views.MatchViewSearchV2.as_view()),
    path('matchs/insert/',views.MatchViewInsert.as_view()),
    path('matchs/searchEquipe/',views.MatchViewSearchEquipe.as_view()),
    path('matchs/delete/<int:pk>/',views.MatchViewRM.as_view()),

    path('statistiquesjoueurs/<int:pk>/',views.StatistiquesJoueurView.as_view()),
    path('statistiquesjoueurs/<int:pk>/',views.StatistiquesJoueurViewRM.as_view()),
    path('statistiquesjoueurs/<int:pk>/',views.StatistiquesJoueurViewUpdate.as_view()),
    path('statistiquesjoueurs/search/',views.StatistiquesJoueurViewSearch.as_view()),
    path('statistiquesjoueurs/search2/',views.StatistiquesJoueurViewSearchV2.as_view()),
    path('statistiquesjoueurs/insert/',views.StatistiquesJoueurViewInsert.as_view()),
    path('statistiquesjoueurs/delete/<int:pk>/',views.StatistiquesJoueurViewRM.as_view()),

    path('statistiquesarbitres/<int:pk>/',views.StatistiquesArbitreView.as_view()),
    path('statistiquesarbitres/<int:pk>/',views.StatistiquesArbitreViewRM.as_view()),
    path('statistiquesarbitres/<int:pk>/',views.StatistiquesArbitreViewUpdate.as_view()),
    path('statistiquesarbitres/search/',views.StatistiquesArbitreViewSearch.as_view()),
    path('statistiquesarbitres/search2/',views.StatistiquesArbitreViewSearchV2.as_view()),
    path('statistiquesarbitres/insert/',views.StatistiquesArbitreViewInsert.as_view()),
    path('statistiquesarbitres/searchArbitre/',views.StatistiquesArbitreViewSearchArbitre.as_view()),
    path('statistiquesarbitres/delete/<int:pk>/',views.StatistiquesArbitreViewRM.as_view()),

    path('transferts/<int:pk>/',views.TransfertView.as_view()),
    path('transferts/<int:pk>/',views.TransfertViewRM.as_view()),
    path('transferts/<int:pk>/',views.TransfertViewUpdate.as_view()),
    path('transferts/search/',views.TransfertViewSearch.as_view()),
    path('transferts/search2/',views.TransfertViewSearchV2.as_view()),
    path('transferts/insert/',views.TransfertViewInsert.as_view()),
    path('transferts/searchEquipe/',views.TransfertViewSearchEquipe.as_view()),
    path('transferts/delete/<int:pk>/',views.TransfertViewRM.as_view()),

    path('championnats/<int:pk>/',views.ChampionnatView.as_view()),
    path('championnats/<int:pk>/',views.ChampionnatViewRM.as_view()),
    path('championnats/<int:pk>/',views.ChampionnatViewUpdate.as_view()),
    path('championnats/search/',views.ChampionnatViewSearch.as_view()),
    path('championnats/search2/',views.ChampionnatViewSearchV2.as_view()),
    path('championnats/insert/',views.ChampionnatViewInsert.as_view()),
    


    path('groupes/<int:pk>/',views.GroupeView.as_view()),
    path('groupes/<int:pk>/',views.GroupeViewRM.as_view()),
    path('groupes/<int:pk>/',views.GroupeViewUpdate.as_view()),
    path('groupes/search/',views.GroupeViewSearch.as_view()),
    path('groupes/search2/',views.GroupeViewSearchV2.as_view()),
    path('groupes/insert/',views.GroupeViewInsert.as_view()),

    path('palmaresclubs/<int:pk>/',views.PalmaresClubView.as_view()),
    path('palmaresclubs/<int:pk>/',views.PalmaresClubViewRM.as_view()),
    path('palmaresclubs/<int:pk>/',views.PalmaresClubViewUpdate.as_view()),
    path('palmaresclubs/search/',views.PalmaresClubViewSearch.as_view()),
    path('palmaresclubs/search2/',views.PalmaresClubViewSearchV2.as_view()),
    path('palmaresClubs/insert/',views.PalmaresClubViewInsert.as_view()),
    path('palmaresclubs/searchClub/',views.PalmaresClubViewSearchClub.as_view()),

    
    

    path('noteArbitres/<int:pk>/',views.NoteArbitreView.as_view()),
    path('noteArbitres/<int:pk>/',views.NoteArbitreViewRM.as_view()),
    path('noteArbitres/<int:pk>/',views.NoteArbitreViewUpdate.as_view()),
    path('noteArbitres/search/',views.NoteArbitreViewSearch.as_view()),
    path('noteArbitres/search2/',views.NoteArbitreViewSearchV2.as_view()),
    path('noteArbitres/insert/',views.NoteArbitreViewInsert.as_view()),

    path('noteJoueurs/<int:pk>/',views.NoteJoueurView.as_view()),
    path('noteJoueurs/<int:pk>/',views.NoteJoueurViewRM.as_view()),
    path('noteJoueurs/<int:pk>/',views.NoteJoueurViewUpdate.as_view()),
    path('noteJoueurs/search/',views.NoteJoueurViewSearch.as_view()),
    path('noteJoueurs/search2/',views.NoteJoueurViewSearchV2.as_view()),
    path('noteJoueurs/insert/',views.NoteJoueurViewInsert.as_view()),


    path('statistiquesEquipes/<int:pk>/',views.StatistiquesEquipeView.as_view()),
    path('statistiquesEquipes/<int:pk>/',views.StatistiquesEquipeViewRM.as_view()),
    path('statistiquesEquipes/<int:pk>/',views.StatistiquesEquipeViewUpdate.as_view()),
    path('statistiquesEquipes/search/',views.StatistiquesEquipeViewSearch.as_view()),
    path('statistiquesEquipes/search2/',views.StatistiquesEquipeViewSearchV2.as_view()),
    path('statistiquesEquipes/insert/',views.StatistiquesEquipeViewInsert.as_view()),
    path('statistiquesEquipes/delete/<int:pk>/',views.StatistiquesEquipeViewRM.as_view()),

    path('buts/<int:pk>/',views.ButView.as_view()),
    path('buts/<int:pk>/',views.ButViewRM.as_view()),
    path('buts/<int:pk>/',views.ButViewUpdate.as_view()),
    path('buts/search/',views.ButViewSearch.as_view()),
    path('buts/search2/',views.ButViewSearchV2.as_view()),
    path('buts/insert/',views.ButViewInsert.as_view()),
    path('buts/delete/<int:pk>/',views.ButViewRM.as_view()),

    path('passeds/<int:pk>/',views.PasseDView.as_view()),
    path('passeds/<int:pk>/',views.PasseDViewRM.as_view()),
    path('passeds/<int:pk>/',views.PasseDViewUpdate.as_view()),
    path('passeds/search/',views.PasseDViewSearch.as_view()),
    path('passeds/search2/',views.PasseDViewSearchV2.as_view()),
    path('passeds/insert/',views.PasseDViewInsert.as_view()),
    path('passeds/delete/<int:pk>/',views.PasseDViewRM.as_view()),

    path('cartons/<int:pk>/',views.CartonView.as_view()),
    path('cartons/<int:pk>/',views.CartonViewRM.as_view()),
    path('cartons/<int:pk>/',views.CartonViewUpdate.as_view()),
    path('cartons/search/',views.CartonViewSearch.as_view()),
    path('cartons/search2/',views.CartonViewSearchV2.as_view()),
    path('cartons/insert/',views.CartonViewInsert.as_view()),
    path('cartons/delete/<int:pk>/',views.CartonViewRM.as_view()),

    path('compositions/<int:pk>/',views.CompositionView.as_view()),
    path('compositions/<int:pk>/',views.CompositionViewRM.as_view()),
    path('compositions/<int:pk>/',views.CompositionViewUpdate.as_view()),
    path('compositions/search/',views.CompositionViewSearch.as_view()),
    path('compositions/search2/',views.CompositionViewSearchV2.as_view()),
    path('compositions/insert/',views.CompositionViewInsert.as_view()),
    path('compositions/delete/<int:pk>/',views.CompositionViewRM.as_view()),
    

    path('noterEntrainements/<int:pk>/',views.NoterEntrainementView.as_view()),
    path('noterEntrainements/<int:pk>/',views.NoterEntrainementViewRM.as_view()),
    path('noterEntrainements/<int:pk>/',views.NoterEntrainementViewUpdate.as_view()),
    path('noterEntrainements/search/',views.NoterEntrainementViewSearch.as_view()),
    path('noterEntrainements/search2/',views.NoterEntrainementViewSearchV2.as_view()),
    path('noterEntrainements/insert/',views.NoterEntrainementViewInsert.as_view()),

    path('noterEntrainementsDistinctDate/search/',views.NoterEntrainementViewSearchDateDistinct.as_view())
]