# Generated by Django 3.2.9 on 2022-05-20 14:31

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('theBest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='poste',
            field=models.ManyToManyField(blank=sqlalchemy.sql.expression.true, to='theBest.Poste'),
        ),
    ]
