# Generated by Django 3.2.9 on 2022-06-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theBest', '0003_notejoueur_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='notearbitre',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theBest.match'),
        ),
    ]
