# Generated by Django 3.2.9 on 2022-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBest', '0005_statistiquesarbitre_nb_matchs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistiquesequipe',
            name='saison',
            field=models.CharField(max_length=30),
        ),
    ]
