# Generated by Django 3.2.9 on 2022-06-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theBest', '0006_alter_statistiquesequipe_saison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistiquesequipe',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theBest.equipe'),
        ),
    ]
