# Generated by Django 3.2.9 on 2022-06-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theBest', '0007_alter_statistiquesequipe_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('mdp', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='classement',
        ),
        migrations.RemoveField(
            model_name='match',
            name='presence',
        ),
        migrations.AlterField(
            model_name='arbitre',
            name='mdp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='mdp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='terrain',
            field=models.ManyToManyField(null=True, to='theBest.Terrain'),
        ),
        migrations.AlterField(
            model_name='entraineur',
            name='diplome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entraineur',
            name='mdp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='joueur',
            field=models.ManyToManyField(null=True, to='theBest.Joueur'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='mdp',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='joueur',
            name='poste',
        ),
        migrations.AddField(
            model_name='joueur',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theBest.poste'),
        ),
        migrations.AlterField(
            model_name='spectateur',
            name='mdp',
            field=models.CharField(max_length=50),
        ),
    ]
